steps:

  # Checkout code
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - clone git@github.com:gabrielpsilva/auther.git

  # Building
  - name: 'gcr.io/cloud-builders/go:debian'
    env:
      - GOPATH=/workspace/gopath
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        cd IntersectBot
        go build -v .

  # Create app docker image and save in google container registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        docker build \
        -t gcr.io/axpress/github.com/gabrielpsilva/intersectbot:latest \
        -f IntersectBot/Dockerfile

  images: ['gcr.io/axpress/github.com/gabrielpsilva/IntersectBot:latest']