steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh master1-2  \
        --zone=us-central1-a \
        -- "
        set -ex
        docker pull gcr.io/axpress/github.com/gabrielpsilva/intersectbot
        docker service update --image gcr.io/axpress/github.com/gabrielpsilva/intersectbot le-bot
        docker service ps le-bot
        "