steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -ex
        docker service update --image gcr.io/axpress/github.com/gabrielpsilva/intersectbot le-bot
        docker service ps le-bot

        "
